{
 "title": "Test Dash",
 "time": { "from": "2023-11-28T20:19:39.962Z", "to": "2023-11-28T20:20:34.714Z" },
 "panels": [
  {
   "title": "In Sync Replicas Count",
   "type": "timeseries",
   "description": "Subset of replicas for a partition that are considered to be in sync with the leader replica. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kafka_cluster_Partition_InSyncReplicasCount{topic!=\"__consumer_offsets\"}",
     "legendFormat": "{{instance}}, partition: {{partition}}, topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "timeseries",
   "description": "Number of unreplicated partitions",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kafka_cluster_Partition_UnderReplicated{topic!=\"__consumer_offsets\"}",
     "legendFormat": "{{instance}}, partition: {{partition}}, topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Replicas Count",
   "type": "timeseries",
   "description": "Number of copies or replicas of a partition that are maintained across different broker nodes in a Kafka cluster. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "kafka_cluster_Partition_ReplicasCount{topic!=\"__consumer_offsets\"}",
     "legendFormat": "{{instance}}, partition: {{partition}}, topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Unclean Leader Election Rate Ms",
   "type": "stat",
   "description": "Number of “unclean” elections per ms",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_controller_ControllerStats_UncleanLeaderElectionEnableRateAndTimeMs_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Error Total",
   "type": "piechart",
   "description": "Measures the total number of network-related errors that occur during communication between clients and the Kafka broker.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_network_RequestMetrics_Errors_total",
     "legendFormat": "{{instance}}, Error: {{error}}, Request: {{request}}"
    }
   ]
  },
  {
   "title": "Total Time Ms",
   "type": "timeseries",
   "description": "Total time (in ms) to serve the specified request (Produce/Fetch)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "kafka_network_RequestMetrics_TotalTimeMs",
     "legendFormat": "{{instance}}, quantile: {{quantile}}, request: {{request}}"
    }
   ]
  },
  {
   "title": "Request Total",
   "type": "piechart",
   "description": "Measures the total number of network requests made to the Kafka broker.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_network_RequestMetrics_Requests_total",
     "legendFormat": "{{instance}}, request: {{request}}, version: {{version}}"
    }
   ]
  },
  {
   "title": "Failed Partitions Count",
   "type": "stat",
   "description": "Number of failed partitions",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_ReplicaFetcherManager_FailedPartitionsCount",
     "legendFormat": "{{instance}}, clientId: {{clientId}}"
    }
   ]
  },
  {
   "title": "Consumer's Lag",
   "type": "timeseries",
   "description": "Number of messages consumer is behind producer on this partition",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "kafka_server_FetcherLagMetrics_ConsumerLag{topic!=\"__consumer_offsets\"}",
     "legendFormat": "{{instance}}, clientId: {{clientId}}, partition: {{partition}}, topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Total Request x Ms",
   "type": "timeseries",
   "description": "Number of (producer|consumer|follower) requests per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "kafka_network_RequestMetrics_TotalTimeMs",
     "legendFormat": "{{instance}}, quantile: {{quantile}}, request: {{request}}"
    }
   ]
  },
  {
   "title": "Failed Producer Request",
   "type": "timeseries",
   "description": "Producer failed to send message to broker.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "kafka_server_BrokerTopicMetrics_FailedProduceRequests_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Broker Bytes In Total",
   "type": "timeseries",
   "description": "Aggregate incoming bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "label_replace(label_replace(kafka_server_BrokerTopicMetrics_BytesIn_total, \"formatted_topic\", \"TOTAL\", \"topic\", \"^$\"), \"formatted_topic\", \"$1\", \"topic\", \"(.+)\")",
     "legendFormat": "{{instance}}, topic: {{formatted_topic}}"
    }
   ]
  },
  {
   "title": "Collection X Seconds Sum",
   "type": "timeseries",
   "description": "The total sum of young or old garbage collection processes executed by the JVM",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    { "expr": "jvm_gc_collection_seconds_sum", "legendFormat": "{{instance}}, gc: {{gc}}" }
   ]
  },
  {
   "title": "Total Producer Request",
   "type": "timeseries",
   "description": "Cumulative number of requests made by producers to the brokers",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "label_replace(label_replace(kafka_server_BrokerTopicMetrics_TotalProduceRequests_total, \"formatted_topic\", \"TOTAL\", \"topic\", \"^$\"), \"formatted_topic\", \"$1\", \"topic\", \"(.+)\")",
     "legendFormat": "{{instance}}, topic: {{formatted_topic}}"
    }
   ]
  },
  {
   "title": "Collection X Seconds Count",
   "type": "timeseries",
   "description": "The total amount of time (in milliseconds) the JVM has spent executing young or old garbage collection processes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count",
     "legendFormat": "{{instance}}, gc: {{gc}}"
    }
   ]
  },
  {
   "title": "Offline Partition Count",
   "type": "gauge",
   "description": "Number of offline partitions",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_controller_KafkaController_OfflinePartitionsCount",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Purgatory Size",
   "type": "timeseries",
   "description": "Number of requests waiting in producer purgatory/Number of requests waiting in fetch purgatory",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "kafka_server_DelayedOperationPurgatory_PurgatorySize",
     "legendFormat": "{{instance}}, Delayed Operation: {{delayedOperation}}"
    }
   ]
  },
  {
   "title": "Replica Manager ISR Shrinks/Expands",
   "type": "timeseries",
   "description": "Rate at which the pool of in-sync replicas (ISRs) shrinks/expands",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "kafka_server_ReplicaManager_IsrShrinks_total",
     "legendFormat": "{{__name__}}, {{instance}}"
    },
    {
     "expr": "kafka_server_ReplicaManager_IsrExpands_total",
     "legendFormat": "{{__name__}}, {{instance}}"
    }
   ]
  },
  {
   "title": "Zookeeper Request Latency Ms",
   "type": "timeseries",
   "description": "The time it takes for Kafka brokers to interact with the Zookeeper ensemble to perform various operations.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "kafka_server_ZooKeeperClientMetrics_ZooKeeperRequestLatencyMs",
     "legendFormat": "{{instance}}, quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "Active Controller Count",
   "type": "gauge",
   "description": "Number of active controllers in cluster",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_controller_KafkaController_ActiveControllerCount",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Houston", "type": "grafana-clock-panel", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 } },
  {
   "title": "Active Broker Count",
   "type": "piechart",
   "description": "Number of active brokers.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_controller_KafkaController_ActiveBrokerCount",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Los Angeles", "type": "grafana-clock-panel", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 } },
  {
   "title": "Broker Bytes Out Total",
   "type": "timeseries",
   "description": "Aggregate outgoing bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "targets": [
    {
     "expr": "kafka_server_BrokerTopicMetrics_BytesOut_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "New York", "type": "grafana-clock-panel", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 } }
 ]
}