apiVersion: 1

# Tells grafana where to look and what for to get metrics
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # orgId: 1
    url: http://localhost:9090
    # basicAuth: false
    isDefault: true
    editable: true