{
 "title": "Test Dash",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Zookeeper Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kafka_server_ZooKeeperClientMetrics_ZooKeeperRequestLatencyMs",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "timeseries",
   "description": "Number of unreplicated partitions",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kafka_cluster_Partition_UnderReplicated",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Collection Count ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unclean Leader Election Rate Ms",
   "type": "stat",
   "description": "Number of “unclean” elections per ms",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_controller_ControllerStats_UncleanLeaderElectionEnableRateAndTimeMs_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Purgatory Size",
   "type": "timeseries",
   "description": "Number of requests waiting in producer purgatory/Number of requests waiting in fetch purgatory",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "kafka_server_DelayedOperationPurgatory_PurgatorySize",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Time Ms",
   "type": "timeseries",
   "description": "Total time (in ms) to serve the specified request (Produce/Fetch)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "kafka_network_RequestMetrics_TotalTimeMs",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Houston", "type": "grafana-clock-panel", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 } },
  {
   "title": "Failed Partitions Count",
   "type": "stat",
   "description": "Number of failed partitions",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_ReplicaFetcherManager_FailedPartitionsCount",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Los Angeles", "type": "grafana-clock-panel", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 } },
  {
   "title": "Total Request x Ms",
   "type": "timeseries",
   "description": "Number of (producer|consumer|follower) requests per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "kafka_network_RequestMetrics_TotalTimeMs",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "New York", "type": "grafana-clock-panel", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 } },
  {
   "title": "Broker Bytes In Total",
   "type": "timeseries",
   "description": "Aggregate incoming bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "kafka_server_BrokerTopicMetrics_BytesIn_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Offline Partition Count",
   "type": "gauge",
   "description": "Number of offline partitions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_controller_KafkaController_OfflinePartitionsCount",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replica Manager ISR Shrinks/Expands",
   "type": "bargauge",
   "description": "Rate at which the pool of in-sync replicas (ISRs) shrinks/expands",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_ReplicaManager_IsrShrinks_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "kafka_server_ReplicaManager_IsrExpands_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Controller Count",
   "type": "state-timeline",
   "description": "Number of active controllers in cluster",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "kafka_controller_KafkaController_ActiveControllerCount",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Broker Count",
   "type": "piechart",
   "description": "Number of active brokers.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_controller_KafkaController_ActiveBrokerCount",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Producer Request",
   "type": "timeseries",
   "description": "Cumulative number of requests made by producers to the brokers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "kafka_server_BrokerTopicMetrics_TotalProduceRequests_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Broker Bytes Out Total",
   "type": "timeseries",
   "description": "Aggregate outgoing bytes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "kafka_server_BrokerTopicMetrics_BytesOut_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}